Repository Coordipai/admin-web, pull requests merged in 2025-05, with the labels that each got.

#8 feat: Add components
  eslint.config.js
  package-lock.json
  package.json
  public/vite.svg
  src/App.jsx
  src/assets/brandIcon.png
  src/components/.gitkeep
  src/components/FormTextarea.jsx
  src/components/Header.jsx
  src/components/SideBar.jsx
  src/pages/.gitkeep
  src/pages/ComponentTest.jsx
  src/styles/globalStyle.js
  src/styles/reset-css.js
  src/styles/theme.js
  vite.config.js
Labels: ✨ 기능

#9 feat: Add project page
  src/App.jsx
  src/assets/icons/arrow-left-icon.svg
  src/assets/icons/arrow-right-icon.svg
  src/assets/icons/edit-icon.svg
  src/assets/icons/trash-icon.svg
  src/components/Common/Button.jsx
  src/components/Common/FileModal.jsx
  src/components/Common/IconButton.jsx
  src/components/Edit/Badge.jsx
  src/components/Edit/DatePicker.jsx
  src/components/Edit/DropDown.jsx
  src/components/Edit/FileTable.jsx
  src/components/Edit/IssueTable.jsx
  src/components/Edit/SearchInputField.jsx
  src/components/Edit/Typography.jsx
  src/components/Edit/UserTable.jsx
  src/pages/ComponentTest.jsx
  src/pages/build_project/BuildProject.jsx
  src/pages/build_project/BuildProject2.jsx
  src/pages/build_project/BuildProject3.jsx
  src/pages/project/Project.jsx
  src/styles/theme.js
Labels: ✨ 기능

#13 feat: Add project setting
  src/App.jsx
  src/components/Edit/UserTable.jsx
  src/pages/build_project/SettingProject.jsx
Labels: ✨ 기능

#20 feat: Add ToastMessage
  package-lock.json
  package.json
  src/App.jsx
  src/pages/ComponentTest.jsx
  src/utils/showToastMsg.js
  vite.config.js
Labels: ✨ 기능

#18 feat: Add PrivateRoute and Use npx standard --fix
  src/App.jsx
  src/components/Common/Button.jsx
  src/components/Common/FileModal.jsx
  src/components/Common/IconButton.jsx
  src/components/Edit/Badge.jsx
  src/components/Edit/DatePicker.jsx
  src/components/Edit/DropDown.jsx
  src/components/Edit/FileTable.jsx
  src/components/Edit/InputField.jsx
  src/components/Edit/IssueTable.jsx
  src/components/Edit/SearchInputField.jsx
  src/components/Edit/Typography.jsx
  src/components/Edit/UserTable.jsx
  src/components/FormTextarea.jsx
  src/components/Header.jsx
  src/components/SideBar.jsx
  src/main.jsx
  src/pages/ComponentTest.jsx
  src/pages/Home.jsx
  src/pages/build_project/BuildProject.jsx
  src/pages/build_project/BuildProject2.jsx
  src/pages/build_project/BuildProject3.jsx
  src/pages/build_project/SettingProject.jsx
  src/pages/issue/IssueDetailPage.jsx
  src/pages/project/Project.jsx
  src/styles/globalStyle.js
  src/styles/reset-css.js
  src/styles/theme.js
Labels: ✨ 기능, 🔨 리팩토링

#25 feat: Add zustand and useProjectStore, useUserStore
  package-lock.json
  package.json
  src/App.jsx
  src/components/SideBar.jsx
  src/mocks/project.js
  src/mocks/user.js
  src/pages/Home.jsx
  src/store/useProjectStore.js
  src/store/useUserStore.js
  src/utils/dateUtils.js
  vite.config.js
Labels: ✨ 기능

#31 feat: Add useAxios hook
  .gitignore
  package-lock.json
  package.json
  src/hooks/.gitkeep
  src/hooks/useAxios.js
Labels: ✨ 기능

#36 feat: Add home api
  src/pages/Home.jsx
Labels: ✨ 기능

#38 feat: Add issueAPI
  src/App.jsx
  src/api/.gitkeep
  src/api/issueApi.js
  src/components/ConfirmModal.jsx
  src/components/SideBar.jsx
  src/mocks/issueList.js
  src/pages/issue/IssueDetailPage.jsx
  src/pages/issue/IssueRequestPage.jsx
  src/pages/issue/IssueSuggestPage.jsx
  src/pages/test/ComponentTest.jsx
  src/pages/test/ProjectTest.jsx
  src/store/useLoadingStore.js
  vite.config.js
Labels: ✨ 기능

#39 feat: Fetchh issues on project
  src/api/issueApi.js
  src/pages/Home.jsx
  src/pages/project/Project.jsx
Labels: ✨ 기능

#40 feat: Add projectbuild api
  package-lock.json
  package.json
  src/App.jsx
  src/components/Common/FileModal.jsx
  src/components/Edit/FileTable.jsx
  src/components/Edit/SearchInputField.jsx
  src/components/Edit/UserTable.jsx
  src/hooks/useAxios.js
  src/main.jsx
  src/pages/build_project/BuildProject.jsx
  src/pages/build_project/BuildProject2.jsx
  src/pages/build_project/BuildProject3.jsx
Labels: ✨ 기능

#45 feat: Add issue auto gen button
  src/components/Common/Button.jsx
  src/pages/project/Project.jsx
Labels: ✨ 기능

#49 fix: Change startdate to korean time
  src/components/Common/FileModal.jsx
  src/components/Edit/FileTable.jsx
  src/pages/Home.jsx
  src/pages/build_project/BuildProject.jsx
Labels: 🐞 버그 수정

#51 Fix: Apply search api
  src/App.jsx
  src/api/useFetchWithTokenRefresh.js
  src/components/Edit/DatePicker.jsx
  src/components/Edit/IssueTable.jsx
  src/components/Edit/SearchInputField.jsx
  src/components/Edit/Typography.jsx
  src/pages/build_project/BuildProject.jsx
  src/pages/build_project/SettingProject.jsx
  src/pages/project/Project.jsx
Labels: 🐞 버그 수정

#53 feat: Add project setting api
  src/components/Edit/SearchInputField.jsx
  src/pages/build_project/SettingProject.jsx
Labels: ✨ 기능

#55 feat: Refactory login logic
  src/api/useFetchWithTokenRefresh.js
  src/pages/Home.jsx
Labels: ✨ 기능

#62 fix: Fix issue table's row to display only unclosed issues
  src/pages/project/Project.jsx
Labels: ✨ 기능

#66 refactory: Refactor axios instance
  src/api/agentApi.js
  src/api/issueApi.js
  src/api/projectApi.js
  src/api/useFetchWithTokenRefresh.js
  src/hooks/useAxios.js
  src/pages/AccountSetupPage/AccountSetupPage.jsx
  src/pages/AccountSetupPage/RepositoryCheckPage.jsx
  src/pages/Home.jsx
  src/pages/UserPage/UserPage.jsx
  src/pages/build_project/BuildProject.jsx
  src/pages/build_project/SettingProject.jsx
  src/pages/issue/IssueRequestPage.jsx
  src/pages/project/Project.jsx
Labels: 🔨 리팩토링

#71 chore: Change column name
  src/components/Edit/IssueTable.jsx
Labels: 🔨 리팩토링

#87 build: Build docker
  .dockerignore
  .github/workflows/deploy.yml
  50x.html
  Dockerfile
  Dockerfile.dev
  README.md
  docker-compose.dev.yml
  nginx/nginx.conf
  src/pages/login/LoginButton.jsx
  src/pages/login/LoginPage.jsx
  vite.config.js
Labels: 🌏 배포

#93 fix: Fix fail get project redirect
  src/pages/Home.jsx
  src/utils/toastMsg.js
Labels: 🐞 버그 수정

#105 refactor: Delete consolelog
  src/components/Edit/DatePicker.jsx
  src/pages/Home.jsx
  src/pages/build_project/BuildProject.jsx
  src/pages/build_project/SettingProject.jsx
  src/pages/issue/IssueRequestPage.jsx
  src/pages/project/Project.jsx
Labels: 🔨 리팩토링
