Repository Coordipai/admin-web, pull requests merged in 2025-06, with the labels that each got.

#117 feat: Add toast Msg
  src/hooks/useAxios.js
  src/pages/Home.jsx
  src/pages/build_project/SettingProject.jsx
Labels: ✨ 기능

#119 Fix/issue request page api
  src/pages/issue/IssueRequestPage.jsx
Labels: ✨ 기능

#121 refactor: Change placeholder
  src/pages/build_project/BuildProject.jsx
  src/pages/build_project/SettingProject.jsx
Labels: 🔨 리팩토링

#123 fix: Add abort event handling in IssueSuggestPage and amend UX things
  src/pages/issue/IssueSuggestPage.jsx
  src/styles/globalStyle.js
Labels: ✨ 기능, 🐞 버그 수정
